apiVersion: v1
kind: Service
metadata:
  name: {{ include "processworker.fullname" . }}
  labels:
    {{- include "processworker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9001
      targetPort: http
      protocol: TCP
      name: http
      targetPort: 9001
  selector:
    {{- include "processworker.selectorLabels" . | nindent 4 }}
